In [24]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [9]:
data = {
    "Age": [25, 30, 35, 40, np.nan, 28],
    "Salary": [50000, 60000, np.nan, 65000, 70000, 48000],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai", "Chennai"],
    "Gender": ["Male", "Female", "Female", "Male", "Female", "Male"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes", "No"]
}
df = pd.DataFrame(data)
df

    Age   Salary     City  Gender Purchased
0  25.0  50000.0    Delhi    Male       Yes
1  30.0  60000.0   Mumbai  Female        No
2  35.0      NaN    Delhi  Female       Yes
3  40.0  65000.0  Chennai    Male        No
4   NaN  70000.0   Mumbai  Female       Yes
5  28.0  48000.0  Chennai    Male        No

In [10]:
imputer = SimpleImputer()
df[["Age", "Salary"]] = imputer.fit_transform(df[["Age", "Salary"]])
df

    Age   Salary     City  Gender Purchased
0  25.0  50000.0    Delhi    Male       Yes
1  30.0  60000.0   Mumbai  Female        No
2  35.0  58600.0    Delhi  Female       Yes
3  40.0  65000.0  Chennai    Male        No
4  31.6  70000.0   Mumbai  Female       Yes
5  28.0  48000.0  Chennai    Male        No

In [14]:
le = LabelEncoder()
df["Purchased"] = le.fit_transform(df["Purchased"])
df

    Age   Salary     City  Gender  Purchased
0  25.0  50000.0    Delhi    Male          1
1  30.0  60000.0   Mumbai  Female          0
2  35.0  58600.0    Delhi  Female          1
3  40.0  65000.0  Chennai    Male          0
4  31.6  70000.0   Mumbai  Female          1
5  28.0  48000.0  Chennai    Male          0

In [21]:
df = pd.get_dummies(df, columns=["City", "Gender"])
df

,Age,Salary,Purchased,City_Chennai,City_Delhi,City_Mumbai,Gender_Female,Gender_Male
0,25.0,50000.0,1,False,True,False,False,True
1,30.0,60000.0,0,False,False,True,True,False
2,35.0,58600.0,1,False,True,False,True,False
3,40.0,65000.0,0,True,False,False,False,True
4,31.6,70000.0,1,False,False,True,True,False
5,28.0,48000.0,0,True,False,False,False,True

In [22]:
# Features aur target separate karo
X = df.drop("Purchased", axis = 1)
y = df["Purchased"]

In [25]:
# Train Test Split karo
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [28]:
# Feature Scaling karo
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print(X_train)

[[-1.27726431 -1.50838634  1.         -0.57735027 -0.57735027 -1.
   1.        ]
 [ 0.30518705 -0.21895931 -1.          1.73205081 -0.57735027  1.
  -1.        ]
 [-0.46343218  1.16778297 -1.         -0.57735027  1.73205081  1.
  -1.        ]
 [ 1.43550944  0.55956268  1.         -0.57735027 -0.57735027 -1.
   1.        ]]