In [11]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [2]:
data = {
    "Age": [25, 30, 35, 40, np.nan, 28],
    "Salary": [50000, 60000, np.nan, 65000, 70000, 48000],
    "Experience": [2, 5, 7, np.nan, 6, 3],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai", "Chennai"],
    "Gender": ["Male", "Female", "Female", "Male", "Female", "Male"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes", "No"]
}

df = pd.DataFrame(data)
df

    Age   Salary  Experience     City  Gender Purchased
0  25.0  50000.0         2.0    Delhi    Male       Yes
1  30.0  60000.0         5.0   Mumbai  Female        No
2  35.0      NaN         7.0    Delhi  Female       Yes
3  40.0  65000.0         NaN  Chennai    Male        No
4   NaN  70000.0         6.0   Mumbai  Female       Yes
5  28.0  48000.0         3.0  Chennai    Male        No

In [3]:
#Target Encode
df["Purchased"] = df["Purchased"].map({"Yes": 1, "No": 0})
df

    Age   Salary  Experience     City  Gender  Purchased
0  25.0  50000.0         2.0    Delhi    Male          1
1  30.0  60000.0         5.0   Mumbai  Female          0
2  35.0      NaN         7.0    Delhi  Female          1
3  40.0  65000.0         NaN  Chennai    Male          0
4   NaN  70000.0         6.0   Mumbai  Female          1
5  28.0  48000.0         3.0  Chennai    Male          0

In [5]:
#Feature / Target Split
X = df.drop("Purchased", axis = 1)
y = df["Purchased"]
print("X => ", X)

X =>      Age   Salary  Experience     City  Gender
0  25.0  50000.0         2.0    Delhi    Male
1  30.0  60000.0         5.0   Mumbai  Female
2  35.0      NaN         7.0    Delhi  Female
3  40.0  65000.0         NaN  Chennai    Male
4   NaN  70000.0         6.0   Mumbai  Female
5  28.0  48000.0         3.0  Chennai    Male

In [32]:
#Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
#Numerical Pipeline
numeric_pipeline = Pipeline([
     ("imputer", SimpleImputer(strategy = "mean")),
    ("scaller", StandardScaler())
])

In [34]:
#Categorical Pipeline
categorical_pipeline = Pipeline([
    ("enccoder", OneHotEncoder())
])

In [35]:
#ColumnTransformer
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, ["Age", "Salary", "Experience"]),
    ("cat", categorical_pipeline, ["City", "Gender"])
])

In [37]:
#Apply Preprocessing
# print(type(X_train))
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print(X_train_processed)

[[-1.48591759 -1.59416228 -1.58518785  1.          0.          0.
   0.          1.        ]
 [ 0.15641238  0.          1.13227703  0.          1.          0.
   1.          0.        ]
 [ 0.          1.10365081  0.45291081  0.          0.          1.
   1.          0.        ]
 [ 1.32950521  0.49051147  0.          1.          0.          0.
   0.          1.        ]]

In [38]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(4, 8)
(2, 8)

In [39]:
df

    Age   Salary  Experience     City  Gender  Purchased
0  25.0  50000.0         2.0    Delhi    Male          1
1  30.0  60000.0         5.0   Mumbai  Female          0
2  35.0      NaN         7.0    Delhi  Female          1
3  40.0  65000.0         NaN  Chennai    Male          0
4   NaN  70000.0         6.0   Mumbai  Female          1
5  28.0  48000.0         3.0  Chennai    Male          0