In [1]:
import pandas as pd

data = {
    "name": ["Aman", "Riya", "Karan", "Neha", "Aman"],
    "age": [23, 25, 22, 24, 23],
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Delhi"],
    "salary": [40000, 50000, 35000, 45000, 40000]
}

df = pd.DataFrame(data)

In [3]:
#Show first 3 rows
df.head(3)

    name  age    city  salary
0   Aman   23   Delhi   40000
1   Riya   25  Mumbai   50000
2  Karan   22   Delhi   35000

In [4]:
#Show last 2 rows
df.tail(2)

   name  age   city  salary
3  Neha   24   Pune   45000
4  Aman   23  Delhi   40000

In [6]:
#Show column names
df.columns

Index(['name', 'age', 'city', 'salary'], dtype='object')

In [7]:
#Show shape of dataframe
df.shape

(5, 4)

In [8]:
#Show data types
df.dtypes

name      object
age        int64
city      object
salary     int64
dtype: object

In [9]:
#Select only name column
df["name"]

0     Aman
1     Riya
2    Karan
3     Neha
4     Aman
Name: name, dtype: object

In [10]:
#Select name and salary columns
df[["name", "salary"]]

    name  salary
0   Aman   40000
1   Riya   50000
2  Karan   35000
3   Neha   45000
4   Aman   40000

In [12]:
#Get ages greater than 23
df[df["age"] > 23]

   name  age    city  salary
1  Riya   25  Mumbai   50000
3  Neha   24    Pune   45000

In [14]:
#Get rows where city is "Delhi"
df[df["city"] == "Delhi"]

    name  age   city  salary
0   Aman   23  Delhi   40000
2  Karan   22  Delhi   35000
4   Aman   23  Delhi   40000

In [15]:
#Get rows where salary > 40000
df[df["salary"] > 40000]

   name  age    city  salary
1  Riya   25  Mumbai   50000
3  Neha   24    Pune   45000

In [17]:
#Get rows where city is Delhi AND age < 24
df[(df["city"] == "Delhi") & (df["age"] < 24)]

    name  age   city  salary
0   Aman   23  Delhi   40000
2  Karan   22  Delhi   35000
4   Aman   23  Delhi   40000

In [19]:
#Sort by salary ascending
df.sort_values("salary")

    name  age    city  salary
2  Karan   22   Delhi   35000
0   Aman   23   Delhi   40000
4   Aman   23   Delhi   40000
3   Neha   24    Pune   45000
1   Riya   25  Mumbai   50000

In [20]:
#Sort by age descending
df.sort_values("age", ascending=False)

    name  age    city  salary
1   Riya   25  Mumbai   50000
3   Neha   24    Pune   45000
0   Aman   23   Delhi   40000
4   Aman   23   Delhi   40000
2  Karan   22   Delhi   35000

In [21]:
#Find average salary
df["salary"].mean()

np.float64(42000.0)

In [22]:
#Find maximum age
df["age"].max()

25

In [27]:
#Count how many people are from Delhi
(df["city"] == "Delhi").sum()

np.int64(3)

In [29]:
#Get average salary per city
df.groupby("city")["salary"].mean()

city
Delhi     38333.333333
Mumbai    50000.000000
Pune      45000.000000
Name: salary, dtype: float64

In [36]:
#Count number of people per city
df.groupby("city")["name"].count()

city
Delhi     3
Mumbai    1
Pune      1
Name: name, dtype: int64

In [40]:
#Check if any duplicate rows exist
df.duplicated().any()

np.True_

In [44]:
#Remove duplicates
df.drop_duplicates(inplace=True)
df

    name  age    city  salary
0   Aman   23   Delhi   40000
1   Riya   25  Mumbai   50000
2  Karan   22   Delhi   35000
3   Neha   24    Pune   45000

In [46]:
#Create new column tax = salary * 0.1
df["tax"] = df["salary"] * 0.1
df

    name  age    city  salary     tax
0   Aman   23   Delhi   40000  4000.0
1   Riya   25  Mumbai   50000  5000.0
2  Karan   22   Delhi   35000  3500.0
3   Neha   24    Pune   45000  4500.0

In [47]:
#Create new column age_after_5_years
df["age_after_5_years"] = df["age"] + 5
df

    name  age    city  salary     tax  age_after_5_years
0   Aman   23   Delhi   40000  4000.0                 28
1   Riya   25  Mumbai   50000  5000.0                 30
2  Karan   22   Delhi   35000  3500.0                 27
3   Neha   24    Pune   45000  4500.0                 29

In [49]:
#Rename salary to monthly_salary
df.rename(columns={"salary":"monthly_salary"}, inplace=True)
df

    name  age    city  monthly_salary     tax  age_after_5_years
0   Aman   23   Delhi           40000  4000.0                 28
1   Riya   25  Mumbai           50000  5000.0                 30
2  Karan   22   Delhi           35000  3500.0                 27
3   Neha   24    Pune           45000  4500.0                 29

In [53]:
df.drop("city", axis=1)

    name  age  monthly_salary     tax  age_after_5_years
0   Aman   23           40000  4000.0                 28
1   Riya   25           50000  5000.0                 30
2  Karan   22           35000  3500.0                 27
3   Neha   24           45000  4500.0                 29