In [1]:
import pandas as pd

data = {
    "user_id": [101, 102, 103, 101, 104, 102, 105],
    "prompt": [
        "Generate Python code",
        "Translate this text",
        None,
        "Summarize article",
        "Generate Python code",
        "Fix bug in code",
        "Translate this text"
    ],
    "category": ["coding", "translation", "writing", "writing", "coding", "coding", "translation"],
    "response_time": [2.5, 3.2, 4.1, None, 2.8, 5.5, 3.0],
    "tokens_used": [250, 180, 300, 220, 260, 400, 190]
}

df = pd.DataFrame(data)
print(df)

   user_id                prompt     category  response_time  tokens_used
0      101  Generate Python code       coding            2.5          250
1      102   Translate this text  translation            3.2          180
2      103                  None      writing            4.1          300
3      101     Summarize article      writing            NaN          220
4      104  Generate Python code       coding            2.8          260
5      102       Fix bug in code       coding            5.5          400
6      105   Translate this text  translation            3.0          190

In [2]:
#First 3 rows
first_3_rows = df.head(3)
print(first_3_rows)
#Last 2 rows
last_2_rows = df.tail(2)
print(last_2_rows)
#Column names
columns_name = df.columns
print(columns_name)
#Data type
print(df.dtypes)

   user_id                prompt     category  response_time  tokens_used
0      101  Generate Python code       coding            2.5          250
1      102   Translate this text  translation            3.2          180
2      103                  None      writing            4.1          300
   user_id               prompt     category  response_time  tokens_used
5      102      Fix bug in code       coding            5.5          400
6      105  Translate this text  translation            3.0          190
Index(['user_id', 'prompt', 'category', 'response_time', 'tokens_used'], dtype='object')
user_id            int64
prompt            object
category          object
response_time    float64
tokens_used        int64
dtype: object

In [3]:
#Get rows where category == "coding"
df[df["category"] == "coding"]

   user_id                prompt category  response_time  tokens_used
0      101  Generate Python code   coding            2.5          250
4      104  Generate Python code   coding            2.8          260
5      102       Fix bug in code   coding            5.5          400

In [4]:
#Get rows where response_time > 3
df[df["response_time"] > 3]

   user_id               prompt     category  response_time  tokens_used
1      102  Translate this text  translation            3.2          180
2      103                 None      writing            4.1          300
5      102      Fix bug in code       coding            5.5          400

In [5]:
#Get rows where tokens_used >= 250
df[df["tokens_used"] >= 250]

   user_id                prompt category  response_time  tokens_used
0      101  Generate Python code   coding            2.5          250
2      103                  None  writing            4.1          300
4      104  Generate Python code   coding            2.8          260
5      102       Fix bug in code   coding            5.5          400

In [6]:
print(df)

   user_id                prompt     category  response_time  tokens_used
0      101  Generate Python code       coding            2.5          250
1      102   Translate this text  translation            3.2          180
2      103                  None      writing            4.1          300
3      101     Summarize article      writing            NaN          220
4      104  Generate Python code       coding            2.8          260
5      102       Fix bug in code       coding            5.5          400
6      105   Translate this text  translation            3.0          190

In [7]:
#Count missing values per column
df.isnull().sum()

user_id          0
prompt           1
category         0
response_time    1
tokens_used      0
dtype: int64

In [8]:
#Replace missing response_time with mean
df["response_time"].fillna(df["response_time"].mean())

0    2.500000
1    3.200000
2    4.100000
3    3.516667
4    2.800000
5    5.500000
6    3.000000
Name: response_time, dtype: float64

In [9]:
#Drop rows where prompt is missing
df.dropna(subset="prompt")

   user_id                prompt     category  response_time  tokens_used
0      101  Generate Python code       coding            2.5          250
1      102   Translate this text  translation            3.2          180
3      101     Summarize article      writing            NaN          220
4      104  Generate Python code       coding            2.8          260
5      102       Fix bug in code       coding            5.5          400
6      105   Translate this text  translation            3.0          190

In [10]:
#Convert all prompts to lowercase
df["prompt"] = df["prompt"].str.lower()
df

   user_id                prompt     category  response_time  tokens_used
0      101  generate python code       coding            2.5          250
1      102   translate this text  translation            3.2          180
2      103                  None      writing            4.1          300
3      101     summarize article      writing            NaN          220
4      104  generate python code       coding            2.8          260
5      102       fix bug in code       coding            5.5          400
6      105   translate this text  translation            3.0          190

In [11]:
#Create new column prompt_length (character count)
df["prompt_length"] = df["prompt"].str.len()
df

,user_id,prompt,category,response_time,tokens_used,prompt_length
0,101,generate python code,coding,2.5,250,20.0
1,102,translate this text,translation,3.2,180,19.0
2,103,None,writing,4.1,300,NaN
3,101,summarize article,writing,NaN,220,17.0
4,104,generate python code,coding,2.8,260,20.0
5,102,fix bug in code,coding,5.5,400,15.0
6,105,translate this text,translation,3.0,190,19.0

In [12]:
#Create new column word_count
df["word_count"] = df["prompt"].str.split().str.len()
df

,user_id,prompt,category,response_time,tokens_used,prompt_length,word_count
0,101,generate python code,coding,2.5,250,20.0,3.0
1,102,translate this text,translation,3.2,180,19.0,3.0
2,103,None,writing,4.1,300,NaN,NaN
3,101,summarize article,writing,NaN,220,17.0,2.0
4,104,generate python code,coding,2.8,260,20.0,3.0
5,102,fix bug in code,coding,5.5,400,15.0,4.0
6,105,translate this text,translation,3.0,190,19.0,3.0

In [13]:
#Total tokens used per user
df.groupby("user_id")["tokens_used"].sum()

user_id
101    470
102    580
103    300
104    260
105    190
Name: tokens_used, dtype: int64

In [14]:
#Average response time per category
df.groupby("category")["response_time"].mean()

category
coding         3.6
translation    3.1
writing        4.1
Name: response_time, dtype: float64

In [15]:
#Count prompts per category
df.groupby("category")["prompt"].count()

category
coding         3
translation    2
writing        1
Name: prompt, dtype: int64

In [16]:
#Sort by tokens_used descending
df.sort_values("tokens_used", ascending=False)

,user_id,prompt,category,response_time,tokens_used,prompt_length,word_count
5,102,fix bug in code,coding,5.5,400,15.0,4.0
2,103,None,writing,4.1,300,NaN,NaN
4,104,generate python code,coding,2.8,260,20.0,3.0
0,101,generate python code,coding,2.5,250,20.0,3.0
3,101,summarize article,writing,NaN,220,17.0,2.0
6,105,translate this text,translation,3.0,190,19.0,3.0
1,102,translate this text,translation,3.2,180,19.0,3.0

In [17]:
#Get top 2 highest token usage rows
df.sort_values("tokens_used", ascending=False).head(2)

,user_id,prompt,category,response_time,tokens_used,prompt_length,word_count
5,102,fix bug in code,coding,5.5,400,15.0,4.0
2,103,None,writing,4.1,300,NaN,NaN

In [22]:
#tokens_per_second = tokens_used / response_time
df["tokens_per_second"] = df["tokens_used"] / df["response_time"]

#Handle division by zero
#df["tokens_per_second"] = df["tokens_used"] / df["response_time"].replace(0, pd.NA)

#If response_time has strings
#df["response_time"] = pd.to_numeric(df["response_time"], errors="coerce")
#df["tokens_per_second"] = df["tokens_used"] / df["response_time"]

df

,user_id,prompt,category,response_time,tokens_used,prompt_length,word_count,tokens_per_second
0,101,generate python code,coding,2.5,250,20.0,3.0,100.000000
1,102,translate this text,translation,3.2,180,19.0,3.0,56.250000
2,103,None,writing,4.1,300,NaN,NaN,73.170732
3,101,summarize article,writing,NaN,220,17.0,2.0,NaN
4,104,generate python code,coding,2.8,260,20.0,3.0,92.857143
5,102,fix bug in code,coding,5.5,400,15.0,4.0,72.727273
6,105,translate this text,translation,3.0,190,19.0,3.0,63.333333

In [27]:
#slow_response → 1 if response_time > 4 else 0
df["slow_response"] = (df["response_time"] > 4).astype(int)
df

,user_id,prompt,category,response_time,tokens_used,prompt_length,word_count,tokens_per_second,slow_response
0,101,generate python code,coding,2.5,250,20.0,3.0,100.000000,0
1,102,translate this text,translation,3.2,180,19.0,3.0,56.250000,0
2,103,None,writing,4.1,300,NaN,NaN,73.170732,1
3,101,summarize article,writing,NaN,220,17.0,2.0,NaN,0
4,104,generate python code,coding,2.8,260,20.0,3.0,92.857143,0
5,102,fix bug in code,coding,5.5,400,15.0,4.0,72.727273,1
6,105,translate this text,translation,3.0,190,19.0,3.0,63.333333,0